@csrf
<div class="grid gap-4 md:grid-cols-2">
    <div><label class="fit-label" for="name">Name</label><input class="fit-input mt-1" id="name" name="name" value="{{ old('name', $plan->name) }}" required></div>
    <div><label class="fit-label" for="goal_type">Goal</label><select class="fit-input mt-1" id="goal_type" name="goal_type">@foreach(['weight_loss'=>'Weight loss','weight_gain'=>'Weight gain','maintenance'=>'Maintenance'] as $v=>$l)<option value="{{ $v }}" @selected(old('goal_type', $plan->goal_type)===$v)>{{ $l }}</option>@endforeach</select></div>
    <div><label class="fit-label" for="dietary_preference">Preference</label><select class="fit-input mt-1" id="dietary_preference" name="dietary_preference">@foreach(['balanced'=>'Balanced','vegetarian'=>'Vegetarian','vegan'=>'Vegan','high_protein'=>'High protein','keto'=>'Keto'] as $v=>$l)<option value="{{ $v }}" @selected(old('dietary_preference', $plan->dietary_preference)===$v)>{{ $l }}</option>@endforeach</select></div>
    <div><label class="fit-label" for="activity_level">Activity</label><select class="fit-input mt-1" id="activity_level" name="activity_level"><option value="">Any</option>@foreach(['sedentary'=>'Sedentary','light'=>'Light','moderate'=>'Moderate','active'=>'Active','athlete'=>'Athlete'] as $v=>$l)<option value="{{ $v }}" @selected(old('activity_level', $plan->activity_level)===$v)>{{ $l }}</option>@endforeach</select></div>
    <div><label class="fit-label" for="calorie_target">Calories</label><input class="fit-input mt-1" id="calorie_target" name="calorie_target" type="number" value="{{ old('calorie_target', $plan->calorie_target) }}" required></div>
    <div><label class="fit-label" for="protein_target_g">Protein g</label><input class="fit-input mt-1" id="protein_target_g" name="protein_target_g" type="number" value="{{ old('protein_target_g', $plan->protein_target_g) }}"></div>
    <div><label class="fit-label" for="carbs_target_g">Carbs g</label><input class="fit-input mt-1" id="carbs_target_g" name="carbs_target_g" type="number" value="{{ old('carbs_target_g', $plan->carbs_target_g) }}"></div>
    <div><label class="fit-label" for="fat_target_g">Fat g</label><input class="fit-input mt-1" id="fat_target_g" name="fat_target_g" type="number" value="{{ old('fat_target_g', $plan->fat_target_g) }}"></div>
    <div class="md:col-span-2"><label class="fit-label" for="description">Description</label><textarea class="fit-input mt-1" id="description" name="description" rows="4">{{ old('description', $plan->description) }}</textarea></div>
    <label class="flex items-center gap-2 text-sm text-slate-200"><input class="rounded border-white/10 bg-slate-950 text-emerald-300" type="checkbox" name="is_active" value="1" @checked(old('is_active', $plan->is_active))> Active</label>
</div>
<div class="mt-6 flex gap-3"><button class="fit-button">{{ $button }}</button><a class="fit-button-secondary" href="{{ route('admin.diet-plans.index') }}">Cancel</a></div>
